#cloud-config
autoinstall:
  version: 1
  identity:
    realname: 'Pedro Henrique Ribeiro'
    hostname: ubuntu-desktop
    username: pedro
    password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
  locale: pt_BR.utf8
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo"
  packages:
    - git
    - openvpn
    - wget
    - curl
    - lm-sensors
    - psensor
    - nvidia-driver-550
  snaps:
    - name: spotify
      channel: stable
      classic: false
    - name: slack
      channel: stable
      classic: true
    - name: teams-for-linux
      channel: stable
      classic: false
    - name: postman
      channel: stable
      classic: true
  codecs:
    install: true
  drivers:
    install: true
  updates: all
  shutdown: reboot
